---
title: "Indicator Species Analysis Boxplot"
author: Carrie Sun, Yanting Xiong
output: html_document
date: "2026-03-20"
---

## Library loading

```{r library_loading}
library(tidyverse)
library(phyloseq)
library(indicspecies)
library(dplyr)
```

## Dataset loading
```{r dataset_loading}
# Load in the filtered and wrangled Parkinson's metadata
parkinsons_metadata_filt_cat = read.csv("../../../Datasets/Metadata/parkinsons_metadata_filt_cat.csv", row.names = 1)

# Relevel the categorical variable in the metadata so that it appears in the order “low,” “medium,” and “high” in the plot, rather than the default alphabetical order
vars = c("Tert_BC", "Tert_AC", "Tert_VA", "Tert_VC", "Tert_VE", "Tert_combine") # store the column names

prefix = c("BC", "AC", "VA", "VC", "VE", "Combine") # stores the label prefixes used in the factor levels

for (i in seq_along(vars)) {
  parkinsons_metadata_filt_cat[[vars[i]]] <- fct_relevel(
    parkinsons_metadata_filt_cat[[vars[i]]],
    paste(prefix[i], "Low"),
    paste(prefix[i], "Medium"),
    paste(prefix[i], "High")
  )
}

# Load in feature table exported from QIIME2
counts = read.delim('../../../QIIME2_outputs/feature-table.txt', skip = 1, row.names = 1)

# Load in taxonomy table exported from QIIME2
taxonomy = read.delim('../../../QIIME2_outputs/taxonomy.tsv', row.names = 1)
```

## Create a Phyloseq Object

```{r phyloseq_object}
# Taxonomy
taxonomy_formatted = taxonomy %>% 
  separate(col = Taxon, 
           into = c("Domain","Phylum","Class","Order",
                    "Family","Genus","Species"),
           sep = ";", fill = "right") %>% 
  select(-Confidence) %>% 
  as.matrix()

# Counts
counts_formatted = counts %>% as.matrix()

# Create the phyloseq object 
ps = phyloseq(sample_data(parkinsons_metadata_filt_cat),
              otu_table(counts_formatted, taxa_are_rows = T),
              tax_table(taxonomy_formatted))

```

## Preprocessing

```{r preprocessing}
# Aggregate ASVs to higher taxonomic level (genus level in this case)
ps_genus = tax_glom(ps, "Genus")

# Convert phyloseq to relative abundance
ps_relab = microbiome::transform(ps, "compositional")

# Extract the otu_table as a data frame because only the otu_table, instead of the phyloseq object, will be used to make plots
otu_table = data.frame(otu_table(ps_relab))

# Extract all the feature IDs from the otu_table
feature_id_extract = rownames(otu_table)

```

## Beta Carotene

### Indicator taxa in the high intake group
```{r beta_carotene_plot}
# Plot the two taxa that are indicators for the high BC intake group
# First one: Cloacibacillus
phyla_to_plot_BC_high_first = feature_id_extract[feature_id_extract %in% "630532cabb74720c1204579e6fe741b4"] 

df_of_taxa_BC_high_first = prune_taxa(phyla_to_plot_BC_high_first, ps_relab) %>% psmelt()

df_of_taxa_BC_high_first %>% 
  ggplot(aes(Tert_BC, Abundance, fill = Tert_BC)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(height = 0, width = 0.2) +
  labs(title = "Relative Abundance of Cloacibacillus Across Dietary Antioxidant Groups in PD", x = "Dietary Antioxidant Tertile", y = "Relative Abundance") +
  scale_x_discrete(labels = c("Low intake", "Medium intake", "High intake")) +
  scale_fill_discrete(
    name = "Beta Carotene Intake Categorization",
    labels = c("Low intake", "Medium intake", "High intake")
  )

# Second one: Alloprevotella
phyla_to_plot_BC_high_second = feature_id_extract[feature_id_extract %in% "a030e5d5ff9c75a027e6cc58ff02cf7c"] 

df_of_taxa_BC_high_second = prune_taxa(phyla_to_plot_BC_high_second, ps_relab) %>% psmelt()

df_of_taxa_BC_high_second %>% 
  ggplot(aes(Tert_BC, Abundance, fill = Tert_BC)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(height = 0, width = 0.2) +
  labs(title = "Relative Abundance of Alloprevotella Across Dietary Antioxidant Groups in PD", x = "Dietary Antioxidant Tertile", y = "Relative Abundance") +
  scale_x_discrete(labels = c("Low intake", "Medium intake", "High intake")) +
  scale_fill_discrete(
    name = "Beta Carotene Intake Categorization",
    labels = c("Low intake", "Medium intake", "High intake")
  )
```