---
title: "Alpha Diversity Analysis Observed Plots"
author: Yanting Xiong
output: html_document
---
## Library loading

```{r libraries, include = FALSE}
library(tidyverse)
library(phyloseq)
library(vegan)
library(broom)
library(ggpubr)
```

## Load the data

```{r load_data}
# Load in the filtered and wrangled Parkinson's metadata
parkinsons_metadata_filt_cat = read.csv('../../../../Datasets/Metadata/parkinsons_metadata_filt_cat.csv', row.names = 1)

# Because we will be controlling for entacapone in downstream analyses and it contains NA values, they need to be removed from the filtered metadata
parkinsons_metadata_filt_cat_entacapone_NA_removed = parkinsons_metadata_filt_cat %>% filter(!is.na(entacapone))
# 10 PD individuals are removed after this filtering step because they do not have entacapone intakes recorded

# Load in feature table exported from QIIME2
counts = read.delim('../../../../QIIME2_outputs/feature-table.txt', skip = 1, row.names = 1)

# Load in taxonomy table exported from QIIME2
taxonomy = read.delim('../../../../QIIME2_outputs/taxonomy.tsv', row.names = 1)
```

## Make a Phyloseq object

```{r Create a Phyloseq object}
taxonomy_formatted = taxonomy %>% 
  separate(col = Taxon,
           into = c("Domain", "Phylum", "Class", "Order", "Family",
                    "Genus", "Species"),
           sep = ";", fill = "right") %>% 
  select(-Confidence) %>% 
  as.matrix()

counts_formatted = counts %>% as.matrix()

ps = phyloseq(sample_data(parkinsons_metadata_filt_cat_entacapone_NA_removed),
              otu_table(counts_formatted, taxa_are_rows = T),
              tax_table(taxonomy_formatted))
```

## Alpha rarefaction curve

```{r alpha_rarefaction}
# Alpha rarefaction curve
rarecurve(t(data.frame(ps@otu_table)),
          step = 1000)

# Based on the alpha rarefaction curve and the PD-filtered-table.qzv results, a sampling depth of 6515 will be chosen because at this sampling depth, only 14 samples are excluded from the analysis and we have retained 1,192,428 (50.04%) features in 183 (92.89%) samples at this specified sampling depth.

# Rarefy the data based on the rarefaction depth chosen
set.seed(421)
psrare = ps %>% rarefy_even_depth(sample.size = 6515, rngseed = 421)
```

## Alpha Diversity Analysis

### Beta carotene

```{r alpha_diversity_analysis_for_beta_carotene}
set.seed(421)

p_BC = plot_richness(psrare, x = "Tert_BC",
                     measures = c("Observed"),
                     color = "Tert_BC")
p_BC

# Modify the graph
# Pull the data from the plot:
pdata_BC = p_BC$data

pdata_BC$Tert_BC = fct_relevel(
  pdata_BC$Tert_BC,
  "BC Low",
  "BC Medium",
  "BC High"
)

str(pdata_BC) # variable denotes metric, value denotes value

# Create p-value data frame
stat.test_BC = data.frame(
  group1 = c("BC Low", "BC Low", "BC Medium"),
  group2 = c("BC High", "BC Medium", "BC High"),
  p = c("0.81", "0.44", "0.81"),
  y.position = c(235, 250, 265)
)

# Graph the plot again
p_BC_formatted = pdata_BC %>% ggplot(aes(Tert_BC, 
                                         value, 
                                         fill = Tert_BC)) +
  geom_boxplot(outlier.shape = NA) + # Don't plot outlier points 
  geom_jitter(height = 0, width = 0.2, size = 0.03) + # Space the points out sideways, reducing overlap
  # Add some formatting
  theme_classic(base_size = 18) +
  facet_wrap(~ variable, ncol = 2, scales = "free_y") +
  ylab("Observed Features") + 
  xlab("Beta-carotene Intake Tertile") + 
  theme(axis.title = element_text(face = "bold")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(fill = "Beta-carotene Intake Categorization") +
  scale_fill_manual(
    values = c("BC Low" = "steelblue", "BC Medium" = "goldenrod2", "BC High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  ) +
  scale_x_discrete(
    labels = c("BC Low" = "Low intake",
               "BC Medium" = "Medium intake",
               "BC High" = "High intake")) +
  stat_pvalue_manual(stat.test_BC, label = "p")
p_BC_formatted

# Export the plot
ggsave("../../../../Results/Figures/Aim_1/Alpha_diversity/Observed/With_p-values/Observed_Beta-carotene.png", plot = p_BC_formatted, width = 10, height = 9, dpi = 300)
```

### Alpha carotene

```{r alpha_diversity_analysis_for_alpha_carotene}
set.seed(421)
p_AC = plot_richness(psrare, x = "Tert_AC",
                     measures = c("Observed"),
                     color = "Tert_AC")
p_AC

# Modify the graph
# Pull the data from the plot:
pdata_AC = p_AC$data

pdata_AC$Tert_AC = fct_relevel(
  pdata_AC$Tert_AC,
  "AC Low",
  "AC Medium",
  "AC High"
)

str(pdata_AC) # variable denotes metric, value denotes value

# Create p-value data frame
stat.test_AC = data.frame(
  group1 = c("AC Low", "AC Low", "AC Medium"),
  group2 = c("AC High", "AC Medium", "AC High"),
  p = c("0.96", "0.96", "1.00"),
  y.position = c(235, 250, 265)
)

# Graph the plot again
p_AC_formatted = pdata_AC %>% ggplot(aes(Tert_AC, 
                                         value, 
                                         fill = Tert_AC)) +
  geom_boxplot(outlier.shape = NA) + # Don't plot outlier points 
  geom_jitter(height = 0, width = 0.2, size = 0.03) + # Space the points out sideways, reducing overlap
  # Add some formatting
  theme_classic(base_size = 18) +
  facet_wrap(~ variable, ncol = 2, scales = "free_y") +
  ylab("Observed Features") + 
  xlab("Alpha-carotene Intake Tertile") +
  theme(axis.title = element_text(face = "bold")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(fill = "Alpha-carotene Intake Categorization") +
  scale_fill_manual(
    values = c("AC Low" = "steelblue", "AC Medium" = "goldenrod2", "AC High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  ) +
  scale_x_discrete(
    labels = c("AC Low" = "Low intake",
               "AC Medium" = "Medium intake",
               "AC High" = "High intake")) + 
  stat_pvalue_manual(stat.test_AC, label = "p")
p_AC_formatted

# Export the plot
ggsave("../../../../Results/Figures/Aim_1/Alpha_diversity/Observed/With_p-values/Observed_Alpha-carotene.png", plot = p_AC_formatted, width = 10, height = 9, dpi = 300)
```

### Vitamin C

```{r alpha_diversity_analysis_for_vitamin_c}
set.seed(421)
p_VC = plot_richness(psrare, x = "Tert_VC",
                     measures = c("Observed"),
                     color = "Tert_VC")
p_VC

# Modify the graph
# Pull the data from the plot:
pdata_VC = p_VC$data

pdata_VC$Tert_VC = fct_relevel(
  pdata_VC$Tert_VC,
  "VC Low",
  "VC Medium",
  "VC High"
)

str(pdata_VC) # variable denotes metric, value denotes value

# Create p-value data frame
stat.test_VC = data.frame(
  group1 = c("VC Low", "VC Low", "VC Medium"),
  group2 = c("VC High", "VC Medium", "VC High"),
  p = c("0.28", "0.79", "0.20"),
  y.position = c(235, 250, 265)
)

# Graph the plot again
p_VC_formatted = pdata_VC %>% ggplot(aes(Tert_VC, 
                                         value, 
                                         fill = Tert_VC)) +
  geom_boxplot(outlier.shape = NA) + # Don't plot outlier points 
  geom_jitter(height = 0, width = 0.2, size = 0.03) + # Space the points out sideways, reducing overlap
  # Add some formatting
  theme_classic(base_size = 18) +
  facet_wrap(~ variable, ncol = 2, scales = "free_y") +
  ylab("Observed Features") + 
  xlab("Vitamin C Intake Tertile") +
  theme(axis.title = element_text(face = "bold")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(fill = "Vitamin C Intake Categorization") +
  scale_fill_manual(
    values = c("VC Low" = "steelblue", "VC Medium" = "goldenrod2", "VC High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  ) +
  scale_x_discrete(
    labels = c("VC Low" = "Low intake",
               "VC Medium" = "Medium intake",
               "VC High" = "High intake")) +
  stat_pvalue_manual(stat.test_VC, label = "p")
p_VC_formatted

# Export the plot
ggsave("../../../../Results/Figures/Aim_1/Alpha_diversity/Observed/With_p-values/Observed_Vitamin_C.png", plot = p_VC_formatted, width = 10, height = 9, dpi = 300)
```

### Vitamin A

```{r alpha_diversity_analysis_for_vitamin_a}
set.seed(421)
p_VA = plot_richness(psrare, x = "Tert_VA",
                     measures = c("Observed"),
                     color = "Tert_VA")
p_VA

# Modify the graph
# Pull the data from the plot:
pdata_VA = p_VA$data

pdata_VA$Tert_VA = fct_relevel(
  pdata_VA$Tert_VA,
  "VA Low",
  "VA Medium",
  "VA High"
)

str(pdata_VA) # variable denotes metric, value denotes value

# Create p-value data frame
stat.test_VA = data.frame(
  group1 = c("VA Low", "VA Low", "VA Medium"),
  group2 = c("VA High", "VA Medium", "VA High"),
  p = c("0.63", "0.49", "0.66"),
  y.position = c(275, 295, 310)
)

# Graph the plot again
p_VA_formatted = pdata_VA %>% ggplot(aes(Tert_VA, 
                                         value, 
                                         fill = Tert_VA)) +
  geom_boxplot(outlier.shape = NA) + # Don't plot outlier points 
  geom_jitter(height = 0, width = 0.2, size = 0.03) + # Space the points out sideways, reducing overlap
  # Add some formatting
  theme_classic(base_size = 18) +
  theme(axis.title = element_text(face = "bold")) +
  facet_wrap(~ variable, ncol = 2, scales = "free_y") +
  ylab("Observed Features") + 
  xlab("Vitamin A Intake Tertile") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(fill = "Vitamin A Intake Categorization") +
  scale_fill_manual(
    values = c("VA Low" = "steelblue", "VA Medium" = "goldenrod2", "VA High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  ) +
  scale_x_discrete(
    labels = c("VA Low" = "Low intake",
               "VA Medium" = "Medium intake",
               "VA High" = "High intake")) +
  stat_pvalue_manual(stat.test_VA, label = "p")
p_VA_formatted

# Export the plot
ggsave("../../../../Results/Figures/Aim_1/Alpha_diversity/Observed/With_p-values/Observed_Vitamin_A.png", plot = p_VA_formatted, width = 10, height = 9, dpi = 300)
```

### Vitamin E

```{r alpha_diversity_analysis_for_vitamin_e}
set.seed(421)
p_VE = plot_richness(psrare, x = "Tert_VE",
                     measures = c("Observed"),
                     color = "Tert_VE")
p_VE

# Modify the graph
# Pull the data from the plot:
pdata_VE = p_VE$data

pdata_VE$Tert_VE = fct_relevel(
  pdata_VE$Tert_VE,
  "VE Low",
  "VE Medium",
  "VE High"
)

str(pdata_VE) # variable denotes metric, value denotes value

# Create p-value data frame
stat.test_VE = data.frame(
  group1 = c("VE Low", "VE Low", "VE Medium"),
  group2 = c("VE High", "VE Medium", "VE High"),
  p = c("0.56", "0.33", "0.56"),
  y.position = c(235, 250, 265)
)

# Graph the plot again
p_VE_formatted = pdata_VE %>% ggplot(aes(Tert_VE, 
                                         value, 
                                         fill = Tert_VE)) +
  geom_boxplot(outlier.shape = NA) + # Don't plot outlier points 
  geom_jitter(height = 0, width = 0.2, size = 0.03) + # Space the points out sideways, reducing overlap
  # Add some formatting
  theme_classic(base_size = 18) +
  theme(axis.title = element_text(face = "bold")) +
  facet_wrap(~ variable, ncol = 2, scales = "free_y") +
  ylab("Observed Features") + 
  xlab("Vitamin E Intake Tertile") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(fill = "Vitamin E Intake Categorization") +
  scale_fill_manual(
    values = c("VE Low" = "steelblue", "VE Medium" = "goldenrod2", "VE High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  ) +
  scale_x_discrete(
    labels = c("VE Low" = "Low intake",
               "VE Medium" = "Medium intake",
               "VE High" = "High intake")) +
  stat_pvalue_manual(stat.test_VE, label = "p")
p_VE_formatted

# Export the plot
ggsave("../../../../Results/Figures/Aim_1/Alpha_diversity/Observed/With_p-values/Observed_Vitamin_E.png", plot = p_VE_formatted, width = 10, height = 9, dpi = 300)

```

### Combine all five dietary antioxidants together

```{r alpha_diversity_analysis_for_all_dietary_antioxidants}
set.seed(421)
p_combine = plot_richness(psrare, x = "Tert_combine",
                          measures = c("Observed"),
                          color = "Tert_combine")
p_combine

# Modify the graph
# Pull the data from the plot:
pdata_combine = p_combine$data

pdata_combine$Tert_combine = fct_relevel(
  pdata_combine$Tert_combine,
  "Combine Low",
  "Combine Medium",
  "Combine High"
)

str(pdata_combine) # variable denotes metric, value denotes value

# Create p-value data frame
stat.test_combine = data.frame(
  group1 = c("Combine Low", "Combine Low", "Combine Medium"),
  group2 = c("Combine High", "Combine Medium", "Combine High"),
  p = c("0.46", "0.32", "0.90"),
  y.position = c(235, 250, 265)
)

# Graph the plot again
p_combine_formatted = pdata_combine %>% ggplot(aes(Tert_combine, 
                                                   value, 
                                                   fill = Tert_combine)) +
  geom_boxplot(outlier.shape = NA) + # Don't plot outlier points 
  geom_jitter(height = 0, width = 0.2, size = 0.03) + # Space the points out sideways, reducing overlap
  # Add some formatting
  theme_classic(base_size = 18) +
  theme(axis.title = element_text(face = "bold")) +
  facet_wrap(~ variable, ncol = 2, scales = "free_y") +
  ylab("Observed Features") + 
  xlab("Combined Intake Tertile") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(fill = "Combined Dietary Antioxidant Intake Categorization") +
  scale_fill_manual(
    values = c("Combine Low" = "steelblue", "Combine Medium" = "goldenrod2", "Combine High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  ) +
  scale_x_discrete(
    labels = c("Combine Low" = "Low intake",
               "Combine Medium" = "Medium intake",
               "Combine High" = "High intake")) +
    stat_pvalue_manual(stat.test_combine, label = "p")
p_combine_formatted

# Export the plot
ggsave("../../../../Results/Figures/Aim_1/Alpha_diversity/Observed/With_p-values/Observed_Combined.png", plot = p_combine_formatted, width = 12, height = 10, dpi = 300)

```