---
title: "Core Microbiome Analysis"
author: Yanting Xiong
output: html_document
date: "2026-04-03"
---

## Library loading

```{r libraries, include = FALSE}
library(tidyverse)
library(phyloseq)
library(dplyr)
library(ggVennDiagram)
library(microbiome)
```

## Load the data

```{r load_data}
# Load in the filtered and wrangled Parkinson's metadata
parkinsons_metadata_filt_cat = read.csv('../../../Datasets/Metadata/parkinsons_metadata_filt_cat.csv', row.names = 1)

# Load in feature table exported from QIIME2
counts = read.delim('../../../QIIME2_outputs/feature-table.txt', skip = 1, row.names = 1)

# Load in taxonomy table exported from QIIME2
taxonomy = read.delim('../../../QIIME2_outputs/taxonomy.tsv', row.names = 1)
```

## Make a Phyloseq object

```{r Create a Phyloseq object}
taxonomy_formatted = taxonomy %>% 
  separate(col = Taxon,
           into = c("Domain", "Phylum", "Class", "Order", "Family",
                    "Genus", "Species"),
           sep = ";", fill = "right") %>% 
  select(-Confidence) %>% 
  as.matrix()

counts_formatted = counts %>% as.matrix()

ps = phyloseq(sample_data(parkinsons_metadata_filt_cat),
              otu_table(counts_formatted, taxa_are_rows = T),
              tax_table(taxonomy_formatted))
```

## Alpha rarefaction curve

```{r alpha_rarefaction}
# Alpha rarefaction curve
rarecurve(t(data.frame(ps@otu_table)),
          step = 1000)

# Based on the alpha rarefaction curve and the PD-filtered-table.qzv results, a sampling depth of 6515 will be chosen because at this sampling depth, only 14 samples are excluded from the analysis and we have retained 1,192,428 (50.04%) features in 183 (92.89%) samples at this specified sampling depth.

# Rarefy the data based on the rarefaction depth chosen
set.seed(421)
psrare = ps %>% rarefy_even_depth(sample.size = 6515, rngseed = 421)
```

## Preparatory work 

```{r}
# Convert to relative abundance
psrare_relab = transform(psrare, "compositional")

# Aggregate the ASVs to the Genus level
psrare_relab_genus = tax_glom(psrare_relab, "Genus")

```

## Beta carotene

```{r beta-carotene}
# Subset the phyloseq object
BC.low = subset_samples(psrare_relab_genus, Tert_BC == "BC Low")
BC.medium = subset_samples(psrare_relab_genus, Tert_BC == "BC Medium")
BC.high = subset_samples(psrare_relab_genus, Tert_BC == "BC High")

# Find core microbiome
ASVs_BC_low = core_members(BC.low, detection = 0, prevalence = 0.5)
ASVs_BC_medium = core_members(BC.medium, detection = 0, prevalence = 0.5)
ASVs_BC_high = core_members(BC.high, detection = 0, prevalence = 0.5)

ggVennDiagram(list(ASVs_BC_low, ASVs_BC_medium, ASVs_BC_high),
              set_size = 6,
              category.names = c("Low Intake", "Medium Intake", "High Intake"))

```