---
title: "Picrust_differential_abundance"
author: "Cynthia"
date: "2026-03-14"
output: html_document
---

```{r libraries, include=FALSE}
library(tidyverse)
library(phyloseq)
library(ggpicrust2)
library(Maaslin2)
```

## R Markdown

Load files
```{r}
metadata = read.csv("../../../Datasets/Metadata/parkinsons_metadata_filt_cat.csv", row.names = 1)
metadata_sub = metadata %>% filter(Tert_combine %in% c("Combine Low", "Combine High")) %>%
  mutate(Tert_combine = fct_drop(as.factor(Tert_combine)))
```

ggpicrust2 to run "Maaslin2", another common differential abundance tool, on your groups of interest and add pathway annotations
```{r}

pathway_abundance = read.delim('../../../QIIME2_outputs/path_abun_unstrat.tsv',row.names = 1)

# Filter
path_filt = pathway_abundance %>% select(all_of(rownames(metadata_sub)))


diff_abun = pathway_daa(abundance = path_filt,
                   metadata = metadata,
                   group = "Tert_combine",
                   daa_method = "Maaslin2",
                   fixed_effects = c("Sex", "Age", "entacapone"),
                   select = NULL,
                   reference = "Combine Low")

daa_annotated_results_df = pathway_annotation(pathway = "MetaCyc",
                                              daa_results_df = diff_abun,
                                              ko_to_kegg = FALSE)
 
# save
saveRDS(daa_annotated_results_df,'daa_annotated_results_df.rds')

readRDS('daa_annotated_results_df.rds')

```
Plots
```{r}
source('../ggpicrust2_errorbar_function_fixed.R')

# Filter out NA in p-values and log2 fold change columns
daa_annotated_results_df_filt = daa_annotated_results_df %>%
  filter(!is.na(p_adjust), !is.na(log2_fold_change))

# Adjusted P-value = 10 hits for plotting (not significant)
daa_annotated_results_df_filt %>% 
  filter(p_adjust < 0.06) %>% 
  nrow()

# Log2 Fold Change values = 15 hits (sufficient for plot)
daa_annotated_results_df_filt %>% 
  filter(abs(log2_fold_change) >= 5e-3) %>% 
  nrow()

# Log2 Fold change values + adjusted p value = 6 hits for plot
daa_annotated_results_df_filt %>% filter(p_adjust< 0.06, abs(log2_fold_change) > 5e-3) %>% nrow()

# Dataframe for plotting
daa_strict <- daa_annotated_results_df_filt %>% 
  filter(p_adjust < 0.06, abs(log2_fold_change) > 5e-3)

# plot
peb = pathway_errorbar_fixed(abundance = path_filt, 
                     daa_results_df = daa_strict, 
                     Group = metadata_sub$Tert_combine, 
                     wrap_label = T, wraplength=60,
                     fc_cutoff = 5e-3, order_by_log = T,
                     p_values_threshold = 0.06, 
                     order = "name", 
                     ko_to_kegg = FALSE, 
                     p_value_bar = TRUE, 
                     x_lab = "description")

# save
ggsave("../../../Results/Figures/Aim_3/Combined/combine-picrust-pathways.png",
       plot = peb, width = 18, height = 10)
```

Heatmap

```{r identical features}
# heatmap library
library('pheatmap')

# working with same pathways as above
sig_features = daa_annotated_results_df %>% 
  filter(p_adjust < 0.06, abs(log2_fold_change) > 5e-3) %>% 
  pull('feature') %>% unique()

path_relab = path_filt %>% 
  apply(2,function(x) x/sum(x)) %>% as.data.frame()
colSums(path_relab) # Should be all 1

stats = path_relab %>% t() %>%  # switch rows and columns
  as.data.frame() %>% # Lets us use select()
  select(all_of(sig_features)) %>% 
  cor(method = 'pearson') #Pearson tests between every feature pair

# Define the color palette
color_palette <- colorRampPalette(c("blue", "white", "red"))(40)

# Define breaks for the color scale
breaks <- seq(-1, 1, length.out = 41)  # 40 colors + 1 for the endpoint

# Lookup Names
name_lookup <- daa_annotated_results_df %>%
  filter(feature %in% sig_features) %>%
  select(feature, description) %>%
  distinct()

readable_names <- name_lookup$description[match(rownames(stats), name_lookup$feature)]
rownames(stats) <- readable_names
colnames(stats) <- readable_names

view(readable_names)

# plot to try to minimize white space
pheatmap(stats, 
         clustering_distance_rows = "euclidean",  
         clustering_distance_cols = "euclidean", 
         clustering_method = "complete",          
         color = color_palette, 
         breaks = breaks,
         border_color = "white",
         display_numbers = TRUE,
         number_format = "%.2f",      
         fontsize_row = 10,
         fontsize_col = 10,
         angle_col = 315,              # rotated to minimize white space
         treeheight_row = 25,         
         treeheight_col = 25, 
         legend = TRUE,               
         main = NA,                   
         filename = "../../../Results/Figures/Aim_3/Combined/MetaCyc-combine_Heatmap_Final-new.png",
         width = 8,                   
         height = 6)

```

PCA plots
```{r PCA}
# Generate pathway PCA plot
pca = pathway_pca(abundance = path_filt,
            metadata = metadata_sub, 
            group = "Tert_combine")

# save pca
ggsave("../../../Results/Figures/Aim_3/Combined/AC-pathway-pca.png", 
       plot = pca, 
       width = 8, 
       height = 6, 
       dpi = 300)
```
