---
title: "Beta Diversity Analysis (Version 1)"
author: Yanting Xiong
output: html_document
date: "2026-03-15"
---
## Library loading

```{r libraries, include = FALSE}
library(tidyverse)
library(phyloseq)
library(vegan)
```

## Dataset loading
```{r load_data}
parkinsons_metadata_filt_cat = read.csv('../../Datasets/Metadata/parkinsons_metadata_filt_cat.csv', row.names = 1)

# Because we will be controlling for entacapone in downstream analyses and it can NA values, they need to be removed form the filtered metadata
parkinsons_metadata_filt_cat_entacapone_NA_removed = parkinsons_metadata_filt_cat %>% filter(!is.na(entacapone))
# 10 PD individuals are removed after this filtering step because they do not have entacapone intakes recorded

# Relevel the categorical variable in the metadata so that it appears in the order “low,” “medium,” and “high” in the plot, rather than the default alphabetical order
parkinsons_metadata_filt_cat_entacapone_NA_removed$Tert_BC = fct_relevel(
  parkinsons_metadata_filt_cat_entacapone_NA_removed$Tert_BC,
  "BC Low",
  "BC Medium",
  "BC High")

parkinsons_metadata_filt_cat_entacapone_NA_removed$Tert_AC = fct_relevel(
  parkinsons_metadata_filt_cat_entacapone_NA_removed$Tert_AC,
  "AC Low",
  "AC Medium",
  "AC High")

parkinsons_metadata_filt_cat_entacapone_NA_removed$Tert_VC = fct_relevel(
  parkinsons_metadata_filt_cat_entacapone_NA_removed$Tert_VC,
  "VC Low",
  "VC Medium",
  "VC High")

parkinsons_metadata_filt_cat_entacapone_NA_removed$Tert_VA = fct_relevel(
  parkinsons_metadata_filt_cat_entacapone_NA_removed$Tert_VA,
  "VA Low",
  "VA Medium",
  "VA High")

parkinsons_metadata_filt_cat_entacapone_NA_removed$Tert_VE = fct_relevel(
  parkinsons_metadata_filt_cat_entacapone_NA_removed$Tert_VE,
  "VE Low",
  "VE Medium",
  "VE High")
  
parkinsons_metadata_filt_cat_entacapone_NA_removed$Tert_combine = fct_relevel(
  parkinsons_metadata_filt_cat_entacapone_NA_removed$Tert_combine,
  "Combine Low",
  "Combine Medium",
  "Combine High") 

counts = read.delim('../../QIIME2_outputs/feature-table.txt', skip = 1, row.names = 1)

taxonomy = read.delim('../../QIIME2_outputs/taxonomy.tsv', row.names = 1)
```

## Make a Phyloseq object

```{r Create a Phyloseq object}
taxonomy_formatted = taxonomy %>% 
  separate(col = Taxon,
           into = c("Domain", "Phylum", "Class", "Order", "Family",
                    "Genus", "Species"),
           sep = ";", fill = "right") %>% 
  select(-Confidence) %>% 
  as.matrix()

counts_formatted = counts %>% as.matrix()

ps = phyloseq(sample_data(parkinsons_metadata_filt_cat_entacapone_NA_removed),
              otu_table(counts_formatted, taxa_are_rows = T),
              tax_table(taxonomy_formatted))
```

## Alpha rarefaction curve

```{r alpha_rarefaction}
# Alpha rarefaction curve
rarecurve(t(data.frame(ps@otu_table)),
          step = 1000)

# Based on the alpha rarefaction curve and the PD-filtered-table.qzv results, a sampling depth of 6515 will be chosen because at this sampling depth, only 14 samples are excluded from the analysis and we have retained 1,192,428 (50.04%) features in 183 (92.89%) samples at this specified sampling depth.

# Rarefy the data based on the rarefaction depth chosen
set.seed(421)
psrare = ps %>% rarefy_even_depth(sample.size = 6515, rngseed = 421)
```

## Beta Diversity Analysis
```{r calculate beta-curtis distances}
ps_bray = phyloseq::distance(psrare, method = "bray")
# View(as.matrix(ps_bray)) # Every pairwise comparison included

# MDS scaling
set.seed(421)
mds = metaMDS(ps_bray)

# Extract data
mds_data = mds$points %>% as.data.frame() %>% 
  merge(sample_data(psrare), by = "row.names", sort = F)
head(mds_data)
```

### Beta carotene
```{r beta_diversity_analysis_for_beta_carotene}
# Plot it
p_BC = mds_data %>% 
  ggplot(aes(MDS1, MDS2, color = Tert_BC)) +
  geom_point() +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  labs(color = "Beta Carotene Intake Categorization")
p_BC

# PERMANOVA test
parkinsons_metadata = sample_data(psrare) %>% data.frame()

# Single variable
stats_univar_BC = adonis2(ps_bray ~ Tert_BC, data = parkinsons_metadata)

# Factor in confounding variables
stats_multivar_BC = adonis2(ps_bray ~ Tert_BC + Age + Sex + Energy_kcal + entacapone, data = parkinsons_metadata, by = "margin")

# Combine into a table
stats_BC = bind_rows("Univariate" = stats_univar_BC %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     "Multivariate" = stats_multivar_BC %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     .id = "Model") # first column is Model, either Uni or Multi

stats_BC = stats_BC %>% rename(Pval = `Pr(>F)`) %>% 
  filter(!is.na(Pval)) # remove irrelevant lines
# Based on the table, both age and entacapone use have p-values below 0.05, indicating that they are significantly associated with variation in the gut microbiome. Therefore, these variables should be accounted for as potential confounders in subsequent statistical analyses.

# List samples that belong to the categories of interest (low and high)
to_compare_BC_LH = c("BC Low", "BC High")

# List samples that belong to these categories of interest 
samples_to_keep_BC_LH = parkinsons_metadata %>% filter(Tert_BC %in% to_compare_BC_LH) %>%
  rownames()

# Subset the distance matrix to only include those two categories of interest
ps_bray_sub_BC_LH = as.matrix(ps_bray)[samples_to_keep_BC_LH, samples_to_keep_BC_LH] %>%
  as.dist()

# Run a PERMANOVA test again and account for the real confounding variables
stats_multivar_BC_LH_rerun = adonis2(ps_bray_sub_BC_LH ~ Tert_BC + Age + entacapone,
                                     data = parkinsons_metadata %>% filter(Tert_BC %in% to_compare_BC_LH))
```

### Alpha carotene
```{r beta_diversity_analysis_for_alpha_carotene}
# Plot it
p_AC = mds_data %>% 
  ggplot(aes(MDS1, MDS2, color = Tert_AC)) +
  geom_point() +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  labs(color = "Alpha Carotene Intake Categorization")
p_AC

# PERMANOVA test
# Single variable
stats_univar_AC = adonis2(ps_bray ~ Tert_AC, data = parkinsons_metadata)

# Factor in confounding variables
stats_multivar_AC = adonis2(ps_bray ~ Tert_AC + Age + Sex + Energy_kcal + entacapone, data = parkinsons_metadata, by = "margin")

# Combine into a table
stats_AC = bind_rows("Univariate" = stats_univar_AC %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     "Multivariate" = stats_multivar_AC %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     .id = "Model") # first column is Model, either Uni or Multi

stats_AC = stats_AC %>% rename(Pval = `Pr(>F)`) %>% 
  filter(!is.na(Pval)) # remove irrelevant lines

# List samples that belong to the categories of interest
to_compare_AC_LH = c("AC Low", "AC High")

# List samples that belong to these categories of interest (low and high)
samples_to_keep_AC_LH = parkinsons_metadata %>% filter(Tert_AC %in% to_compare_AC_LH) %>%
  rownames()

# Subset the distance matrix to only include those two categories of interest
ps_bray_sub_AC_LH = as.matrix(ps_bray)[samples_to_keep_AC_LH, samples_to_keep_AC_LH] %>%
  as.dist()

# Run a PERMANOVA test again and account for the real confounding variables
stats_multivar_AC_LH_rerun = adonis2(ps_bray_sub_AC_LH ~ Tert_AC + Age + entacapone,
                                     data = parkinsons_metadata %>% filter(Tert_AC %in% to_compare_AC_LH))
```

### Vitamin C
```{r beta_diversity_analysis_for_vitamin_c}
# Plot it
p_VC = mds_data %>% 
  ggplot(aes(MDS1, MDS2, color = Tert_VC)) +
  geom_point() +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  labs(color = "Vitamin C Intake Categorization")
p_VC

# PERMANOVA test
# Single variable
stats_univar_VC = adonis2(ps_bray ~ Tert_VC, data = parkinsons_metadata)

# Factor in confounding variables
stats_multivar_VC = adonis2(ps_bray ~ Tert_VC + Age + Sex + Energy_kcal + entacapone, data = parkinsons_metadata, by = "margin")

# Combine into a table
stats_VC = bind_rows("Univariate" = stats_univar_VC %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     "Multivariate" = stats_multivar_VC %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     .id = "Model") # first column is Model, either Uni or Multi

stats_VC = stats_VC %>% rename(Pval = `Pr(>F)`) %>% 
  filter(!is.na(Pval)) # remove irrelevant lines

# List samples that belong to the categories of interest
to_compare_VC_LH = c("VC Low", "VC High")

# List samples that belong to these categories of interest (low and high)
samples_to_keep_VC_LH = parkinsons_metadata %>% filter(Tert_VC %in% to_compare_VC_LH) %>%
  rownames()

# Subset the distance matrix to only include those two categories of interest
ps_bray_sub_VC_LH = as.matrix(ps_bray)[samples_to_keep_VC_LH, samples_to_keep_VC_LH] %>%
  as.dist()

# Run a PERMANOVA test again and account for the real confounding variables
stats_multivar_VC_LH_rerun = adonis2(ps_bray_sub_VC_LH ~ Tert_VC + Age + entacapone,
                                     data = parkinsons_metadata %>% filter(Tert_VC %in% to_compare_VC_LH))

```
### Vitamin A
```{r beta_diversity_analysis_for_vitamin_a}
# Plot it
p_VA = mds_data %>% 
  ggplot(aes(MDS1, MDS2, color = Tert_VA)) +
  geom_point() +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  labs(color = "Vitamin A Intake Categorization")
p_VA

# PERMANOVA test
# Single variable
stats_univar_VA = adonis2(ps_bray ~ Tert_VA, data = parkinsons_metadata)

# Factor in confounding variables
stats_multivar_VA = adonis2(ps_bray ~ Tert_VA + Age + Sex + Energy_kcal + entacapone, data = parkinsons_metadata, by = "margin")

# Combine into a table
stats_VA = bind_rows("Univariate" = stats_univar_VA %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     "Multivariate" = stats_multivar_VA %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     .id = "Model") # first column is Model, either Uni or Multi

stats_VA = stats_VA %>% rename(Pval = `Pr(>F)`) %>% 
  filter(!is.na(Pval)) # remove irrelevant lines

# List samples that belong to the categories of interest
to_compare_VA_LH = c("VA Low", "VA High")

# List samples that belong to these categories of interest (low and high)
samples_to_keep_VA_LH = parkinsons_metadata %>% filter(Tert_VA %in% to_compare_VA_LH) %>%
  rownames()

# Subset the distance matrix to only include those two categories of interest
ps_bray_sub_VA_LH = as.matrix(ps_bray)[samples_to_keep_VA_LH, samples_to_keep_VA_LH] %>%
  as.dist()

# Run a PERMANOVA test again and account for the real confounding variables
stats_multivar_VA_LH_rerun = adonis2(ps_bray_sub_VA_LH ~ Tert_VA + Age + entacapone,
                                     data = parkinsons_metadata %>% filter(Tert_VA %in% to_compare_VA_LH))

```
### Vitamin E
```{r beta_diversity_analysis_for_vitamin_e}
# Plot it
p_VE = mds_data %>% 
  ggplot(aes(MDS1, MDS2, color = Tert_VE)) +
  geom_point() +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  labs(color = "Vitamin E Intake Categorization")
p_VE

# PERMANOVA test
# Single variable
stats_univar_VE = adonis2(ps_bray ~ Tert_VE, data = parkinsons_metadata)

# Factor in confounding variables
stats_multivar_VE = adonis2(ps_bray ~ Tert_VE + Age + Sex + Energy_kcal + entacapone, data = parkinsons_metadata, by = "margin")

# Combine into a table
stats_VE = bind_rows("Univariate" = stats_univar_VE %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     "Multivariate" = stats_multivar_VE %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     .id = "Model") # first column is Model, either Uni or Multi

stats_VE = stats_VE %>% rename(Pval = `Pr(>F)`) %>% 
  filter(!is.na(Pval)) # remove irrelevant lines

# List samples that belong to the categories of interest
to_compare_VE_LH = c("VE Low", "VE High")

# List samples that belong to these categories of interest (low and high)
samples_to_keep_VE_LH = parkinsons_metadata %>% filter(Tert_VE %in% to_compare_VE_LH) %>%
  rownames()

# Subset the distance matrix to only include those two categories of interest
ps_bray_sub_VE_LH = as.matrix(ps_bray)[samples_to_keep_VE_LH, samples_to_keep_VE_LH] %>%
  as.dist()

# Run a PERMANOVA test again and account for the real confounding variables
stats_multivar_VE_LH_rerun = adonis2(ps_bray_sub_VE_LH ~ Tert_VE + Age + entacapone,
                                     data = parkinsons_metadata %>% filter(Tert_VE %in% to_compare_VE_LH))

```

### Five dietary antioxidants combined together
```{r beta_diversity_analysis_for_combined_dietary_antioxidants}
# Plot it
p_combine = mds_data %>% 
  ggplot(aes(MDS1, MDS2, color = Tert_combine)) +
  geom_point() +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  labs(color = "Combined Intake Categorization")
p_combine

# PERMANOVA test
# Single variable
stats_univar_combine = adonis2(ps_bray ~ Tert_combine, data = parkinsons_metadata)

# Factor in confounding variables
stats_multivar_combine = adonis2(ps_bray ~ Tert_combine + Age + Sex + Energy_kcal + entacapone, data = parkinsons_metadata, by = "margin")

# Combine into a table
stats_combine = bind_rows("Univariate" = stats_univar_combine %>% as.data.frame() %>% 
                            rownames_to_column("Variable"),
                          "Multivariate" = stats_multivar_combine %>% as.data.frame() %>%
                            rownames_to_column("Variable"),
                          .id = "Model") # first column is Model, either Uni or Multi

stats_combine = stats_combine %>% rename(Pval = `Pr(>F)`) %>% 
  filter(!is.na(Pval)) # remove irrelevant lines

# List samples that belong to the categories of interest
to_compare_combine_LH = c("Combine Low", "Combine High")

# List samples that belong to these categories of interest (low and high)
samples_to_keep_combine_LH = parkinsons_metadata %>% filter(Tert_combine %in% to_compare_combine_LH) %>%
  rownames()

# Subset the distance matrix to only include those two categories of interest
ps_bray_sub_combine_LH = as.matrix(ps_bray)[samples_to_keep_combine_LH, samples_to_keep_combine_LH] %>%
  as.dist()

# Run a PERMANOVA test again and account for the real confounding variables
stats_multivar_combine_LH_rerun = adonis2(ps_bray_sub_combine_LH ~ Tert_combine + Age + entacapone,
                                     data = parkinsons_metadata %>% filter(Tert_combine %in% to_compare_combine_LH))
```