---
title: "Differential Abundance Analysis"
author: Yanting Xiong
output: html_document
date: "2026-03-14"
---

## Library loading
```{r library loading}
library(tidyverse)
library(phyloseq)
library(ANCOMBC)
```

## Dataset loading
```{r dataset loading}
# Load in the filtered and wrangled Parkinson's metadata
parkinsons_metadata_filt_cat = read.csv("../../Datasets/Metadata/parkinsons_metadata_filt_cat.csv", row.names = 1)

# Because we will be controlling for entacapone in downstream analyses and it contains NA values, they need to be removed from the filtered metadata
parkinsons_metadata_filt_cat_entacapone_NA_removed = parkinsons_metadata_filt_cat %>% filter(!is.na(entacapone))
# 10 PD individuals are removed after this filtering step because they do not have entacapone intakes recorded



taxonomy = read.delim("../../QIIME2_outputs/taxonomy.tsv", row.names = 1)

counts = read.delim("../../QIIME2_outputs/feature-table.txt", skip = 1, row.names = 1)
```

## Makr a Phyloseq object
```{r phyloseq object}
# Taxonomy
taxonomy_formatted = taxonomy %>% 
  separate(col = Taxon, 
           into = c("Domain","Phylum","Class","Order",
                    "Family","Genus","Species"),
           sep = ";", fill = "right") %>% 
  select(-Confidence) %>% 
  as.matrix()

# Counts
counts_formatted = counts %>% as.matrix()

# Create the phyloseq object
ps = phyloseq(sample_data(parkinsons_metadata_filt_cat),
              otu_table(counts_formatted, taxa_are_rows = T),
              tax_table(taxonomy_formatted))
```

## Preprocessing
```{r pre-processing}
ps_genus = tax_glom(ps, "Genus")

temp_relab = microbiome::transform(ps_genus, "compositional")

temp_filt = filter_taxa(temp_relab, function(x) mean(x) >= 0.0001, TRUE)

# Filter the raw count phyloseq object to only include taxa in ps_filt
ps_filt = prune_taxa(taxa_names(temp_filt), ps_genus)
```

## Alpha Carotene
```{r}
set.seed(421)
out_VC = ancombc2(data = ps_filt,
               fix_formula = "Tert_VC + Age + Sex + entacapone",
               p_adj_method = "BH",
               prv_cut = 0.1)
```