---
title: "Beta Diversity Analysis using Unweighted UniFrac"
author: Coe McGrath
output: html_document
date: "2026-03-27"
---

## Library loading

```{r libraries, include = FALSE}
library(tidyverse)
library(phyloseq)
library(vegan)
library(ape)
```

## Dataset loading and wrangling

```{r load_data}
# Load in the filtered and wrangled Parkinson's metadata
parkinsons_metadata_filt_cat = read.csv('../../../Datasets/Metadata/parkinsons_metadata_filt_cat.csv', row.names = 1)

# Because we will be controlling for entacapone in downstream analyses and it contains NA values, they need to be removed from the filtered metadata
parkinsons_metadata_filt_cat_entacapone_NA_removed = parkinsons_metadata_filt_cat %>% filter(!is.na(entacapone))
# 10 PD individuals are removed after this filtering step because they do not have entacapone intakes recorded

# Relevel the categorical variable in the metadata so that it appears in the order “low,” “medium,” and “high” in the plot, rather than the default alphabetical order
vars = c("Tert_BC", "Tert_AC", "Tert_VA", "Tert_VC", "Tert_VE", "Tert_combine") # store the column names

prefix = c("BC", "AC", "VA", "VC", "VE", "Combine") # stores the label prefixes used in the factor levels

for (i in seq_along(vars)) {
  parkinsons_metadata_filt_cat_entacapone_NA_removed[[vars[i]]] <- fct_relevel(
    parkinsons_metadata_filt_cat_entacapone_NA_removed[[vars[i]]],
    paste(prefix[i], "Low"),
    paste(prefix[i], "Medium"),
    paste(prefix[i], "High")
  )
}

# Load in feature table exported from QIIME2
counts = read.delim('../../../QIIME2_outputs/feature-table.txt', skip = 1, row.names = 1)

# Load in taxonomy table exported from QIIME2
taxonomy = read.delim('../../../QIIME2_outputs/taxonomy.tsv', row.names = 1)

# Load in phylogenetic tree exported from QIIME2
tree <- read_tree('../../../QIIME2_outputs/tree.nwk')
```

## Make a Phyloseq object

```{r Create a Phyloseq object}
taxonomy_formatted = taxonomy %>% 
  separate(col = Taxon,
           into = c("Domain", "Phylum", "Class", "Order", "Family",
                    "Genus", "Species"),
           sep = ";", fill = "right") %>% 
  select(-Confidence) %>% 
  as.matrix()

counts_formatted = counts %>% as.matrix()

ps = phyloseq(sample_data(parkinsons_metadata_filt_cat_entacapone_NA_removed),
              otu_table(counts_formatted, taxa_are_rows = T),
              tax_table(taxonomy_formatted),
              phy_tree(tree))

# Check if tip names match the ASV IDs
all(taxa_names(ps) %in% tree$tip.label) # Returns TRUE
```

## Alpha rarefaction curve

```{r alpha_rarefaction}
# Alpha rarefaction curve
rarecurve(t(data.frame(ps@otu_table)),
          step = 1000)

# Based on the alpha rarefaction curve and the PD-filtered-table.qzv results, a sampling depth of 6515 will be chosen because at this sampling depth, only 14 samples are excluded from the analysis and we have retained 1,192,428 (50.04%) features in 183 (92.89%) samples at this specified sampling depth.

# Rarefy the data based on the rarefaction depth chosen
set.seed(421)
psrare = ps %>% rarefy_even_depth(sample.size = 6515, rngseed = 421)
```

## Calculate Unweighted UniFrac Distances

```{r calculate Weighted UniFrac Distances}
ps_unweighted_unifrac = phyloseq::distance(psrare, method = "unifrac")

# View(as.matrix(ps_weighted_unifrac)) # Every pairwise comparison included

# MDS scaling
set.seed(421)
mds = metaMDS(ps_unweighted_unifrac)

# Extract data
mds_data <- mds$points %>% 
  as.data.frame() %>% 
  merge(sample_data(psrare), by = "row.names", sort = F)
head(mds_data)

```

### Beta carotene

```{r beta_diversity_analysis_for_beta_carotene}
# Plot it
p_BC = mds_data %>% 
  ggplot(aes(MDS1, MDS2, color = Tert_BC)) +
  geom_point() +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  labs(color = "Beta Carotene Intake Categorization") +
  scale_color_manual(
    values = c("BC Low" = "goldenrod2", "BC Medium" = "steelblue", "BC High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  )
p_BC

parkinsons_metadata = sample_data(psrare) %>% data.frame()

# PERMANOVA test
# Single variable
set.seed(421)
stats_univar_BC = adonis2(ps_unweighted_unifrac ~ Tert_BC, data = parkinsons_metadata)

# Factor in confounding variables
set.seed(421)
stats_multivar_BC = adonis2(ps_unweighted_unifrac ~ Tert_BC + Age + Sex + entacapone, data = parkinsons_metadata, by = "margin")

# Combine into a table
stats_BC = bind_rows("Univariate" = stats_univar_BC %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     "Multivariate" = stats_multivar_BC %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     .id = "Model") # first column is Model, either Uni or Multi

stats_BC = stats_BC %>% rename(Pval = `Pr(>F)`) %>% 
  filter(!is.na(Pval)) # remove irrelevant lines

```

#### "BC Low" vs. "BC High"

```{r}
# List samples that belong to the categories of interest (low and high)
to_compare_BC_LH = c("BC Low", "BC High")

# List samples that belong to these categories of interest 
samples_to_keep_BC_LH = parkinsons_metadata %>% filter(Tert_BC %in% to_compare_BC_LH) %>%
  rownames()

# Subset the distance matrix to only include those two categories of interest
ps_unweighted_unifrac_sub_BC_LH = as.matrix(ps_unweighted_unifrac)[samples_to_keep_BC_LH, samples_to_keep_BC_LH] %>%
  as.dist()

# Run a PERMANOVA test again and account for the real confounding variables
set.seed(421)
stats_unweighted_multivar_BC_LH = adonis2(ps_unweighted_unifrac_sub_BC_LH ~ Tert_BC + Age + entacapone + Sex,
                                          data = parkinsons_metadata %>% filter(Tert_BC %in% to_compare_BC_LH)) # p-value is 0.04

```


### Alpha carotene

```{r beta_diversity_analysis_for_alpha_carotene}
# Plot it
p_AC = mds_data %>% 
  ggplot(aes(MDS1, MDS2, color = Tert_AC)) +
  geom_point() +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  labs(color = "Alpha Carotene Intake Categorization") +
  scale_color_manual(
    values = c("AC Low" = "goldenrod2", "AC Medium" = "steelblue", "AC High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  )
p_AC

# PERMANOVA test
# Single variable
set.seed(421)
stats_univar_AC = adonis2(ps_unweighted_unifrac ~ Tert_AC, data = parkinsons_metadata)

# Factor in confounding variables
set.seed(421)
stats_multivar_AC = adonis2(ps_unweighted_unifrac ~ Tert_AC + Age + Sex + entacapone, data = parkinsons_metadata, by = "margin")

# Combine into a table
stats_AC = bind_rows("Univariate" = stats_univar_AC %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     "Multivariate" = stats_multivar_AC %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     .id = "Model") # first column is Model, either Uni or Multi

stats_AC = stats_AC %>% rename(Pval = `Pr(>F)`) %>% 
  filter(!is.na(Pval)) # remove irrelevant lines
```

#### "AC Low" vs. "AC High"

```{r}
# List samples that belong to the categories of interest
to_compare_AC_LH = c("AC Low", "AC High")

# List samples that belong to these categories of interest (low and high)
samples_to_keep_AC_LH = parkinsons_metadata %>% filter(Tert_AC %in% to_compare_AC_LH) %>%
  rownames()

# Subset the distance matrix to only include those two categories of interest
ps_unweighted_unifrac_sub_AC_LH = as.matrix(ps_unweighted_unifrac)[samples_to_keep_AC_LH, samples_to_keep_AC_LH] %>%
  as.dist()

# Run a PERMANOVA test again and account for the real confounding variables
set.seed(421)
stats_unweighted_multivar_AC_LH = adonis2(ps_unweighted_unifrac_sub_AC_LH ~ Tert_AC + Age + entacapone + Sex,
                                          data = parkinsons_metadata %>% filter(Tert_AC %in% to_compare_AC_LH)) # p-value is 0.28
```


### Vitamin C

```{r beta_diversity_analysis_for_vitamin_c}
# Plot it
p_VC = mds_data %>% 
  ggplot(aes(MDS1, MDS2, color = Tert_VC)) +
  geom_point() +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  labs(color = "Vitamin C Intake Categorization") +
  scale_color_manual(
    values = c("VC Low" = "goldenrod2", "VC Medium" = "steelblue", "VC High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  )
p_VC

# PERMANOVA test
# Single variable
set.seed(421)
stats_univar_VC = adonis2(ps_unweighted_unifrac ~ Tert_VC, data = parkinsons_metadata)

# Factor in confounding variables
set.seed(421)
stats_multivar_VC = adonis2(ps_unweighted_unifrac ~ Tert_VC + Age + Sex + entacapone, data = parkinsons_metadata, by = "margin")

# Combine into a table
stats_VC = bind_rows("Univariate" = stats_univar_VC %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     "Multivariate" = stats_multivar_VC %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     .id = "Model") # first column is Model, either Uni or Multi

stats_VC = stats_VC %>% rename(Pval = `Pr(>F)`) %>% 
  filter(!is.na(Pval)) # remove irrelevant lines
```

#### "VC Low" vs. "VC High"

```{r}
# List samples that belong to the categories of interest
to_compare_VC_LH = c("VC Low", "VC High")

# List samples that belong to these categories of interest (low and high)
samples_to_keep_VC_LH = parkinsons_metadata %>% filter(Tert_VC %in% to_compare_VC_LH) %>%
  rownames()

# Subset the distance matrix to only include those two categories of interest
ps_unweighted_unifrac_sub_VC_LH = as.matrix(ps_unweighted_unifrac)[samples_to_keep_VC_LH, samples_to_keep_VC_LH] %>%
  as.dist()

# Run a PERMANOVA test again and account for the real confounding variables
set.seed(421)
stats_unweighted_multivar_VC_LH = adonis2(ps_unweighted_unifrac_sub_VC_LH ~ Tert_VC + Age + entacapone + Sex,
                                          data = parkinsons_metadata %>% filter(Tert_VC %in% to_compare_VC_LH)) # p-value is 0.033

```


### Vitamin A

```{r beta_diversity_analysis_for_vitamin_a}
# Plot it
p_VA = mds_data %>% 
  ggplot(aes(MDS1, MDS2, color = Tert_VA)) +
  geom_point() +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  labs(color = "Vitamin A Intake Categorization") +
  scale_color_manual(
    values = c("VA Low" = "goldenrod2", "VA Medium" = "steelblue", "VA High" = "indianred3", title = "Beta Diversity Analysis on Varying Levels of Vitamin A Intake"),
    labels = c("Low intake", "Medium intake", "High intake")
  )
p_VA

# PERMANOVA test
# Single variable
set.seed(421)
stats_univar_VA = adonis2(ps_unweighted_unifrac ~ Tert_VA, data = parkinsons_metadata)

# Factor in confounding variables
set.seed(421)
stats_multivar_VA = adonis2(ps_unweighted_unifrac ~ Tert_VA + Age + Sex + entacapone, data = parkinsons_metadata, by = "margin")

# Combine into a table
stats_VA = bind_rows("Univariate" = stats_univar_VA %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     "Multivariate" = stats_multivar_VA %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     .id = "Model") # first column is Model, either Uni or Multi

stats_VA = stats_VA %>% rename(Pval = `Pr(>F)`) %>% 
  filter(!is.na(Pval)) # remove irrelevant lines
```

#### "VA Low vs. "VA High"

```{r}
# List samples that belong to the categories of interest
to_compare_VA_LH = c("VA Low", "VA High")

# List samples that belong to these categories of interest (low and high)
samples_to_keep_VA_LH = parkinsons_metadata %>% filter(Tert_VA %in% to_compare_VA_LH) %>%
  rownames()

# Subset the distance matrix to only include those two categories of interest
ps_unweighted_unifrac_sub_VA_LH = as.matrix(ps_unweighted_unifrac)[samples_to_keep_VA_LH, samples_to_keep_VA_LH] %>%
  as.dist()

# Run a PERMANOVA test again and account for the real confounding variables
set.seed(421)
stats_unweighted_multivar_VA_LH = adonis2(ps_unweighted_unifrac_sub_VA_LH ~ Tert_VA + Age + entacapone + Sex,
                                          data = parkinsons_metadata %>% filter(Tert_VA %in% to_compare_VA_LH)) # p-value is 0.116

```

### Vitamin E

```{r beta_diversity_analysis_for_vitamin_e}
# Plot it
p_VE = mds_data %>% 
  ggplot(aes(MDS1, MDS2, color = Tert_VE)) +
  geom_point() +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  labs(color = "Vitamin E Intake Categorization") +
  scale_color_manual(
    values = c("VE Low" = "goldenrod2", "VE Medium" = "steelblue", "VE High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  )
p_VE

# PERMANOVA test
# Single variable
set.seed(421)
stats_univar_VE = adonis2(ps_unweighted_unifrac ~ Tert_VE, data = parkinsons_metadata)

# Factor in confounding variables
set.seed(421)
stats_multivar_VE = adonis2(ps_unweighted_unifrac ~ Tert_VE + Age + Sex + entacapone, data = parkinsons_metadata, by = "margin")

# Combine into a table
stats_VE = bind_rows("Univariate" = stats_univar_VE %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     "Multivariate" = stats_multivar_VE %>% as.data.frame() %>% 
                       rownames_to_column("Variable"),
                     .id = "Model") # first column is Model, either Uni or Multi

stats_VE = stats_VE %>% rename(Pval = `Pr(>F)`) %>% 
  filter(!is.na(Pval)) # remove irrelevant lines
```

#### "VE Low" vs "VE High"

```{r}
# List samples that belong to the categories of interest (low and high)
to_compare_VE_LH = c("VE Low", "VE High")

# List samples that belong to these categories of interest
samples_to_keep_VE_LH = parkinsons_metadata %>% filter(Tert_VE %in% to_compare_VE_LH) %>%
  rownames()

# Subset the distance matrix to only include those two categories of interest
ps_unweighted_unifrac_sub_VE_LH = as.matrix(ps_unweighted_unifrac)[samples_to_keep_VE_LH, samples_to_keep_VE_LH] %>%
  as.dist()

# Run a PERMANOVA test again and account for the real confounding variables
set.seed(421)
stats_unweighted_multivar_VE_LH = adonis2(ps_unweighted_unifrac_sub_VE_LH ~ Tert_VE + Age + entacapone + Sex,
                                          data = parkinsons_metadata %>% filter(Tert_VE %in% to_compare_VE_LH)) # p-value is 0.001

```


### Five dietary antioxidants combined together

```{r beta_diversity_analysis_for_combined_dietary_antioxidants}
# Plot it
p_combine = mds_data %>% 
  ggplot(aes(MDS1, MDS2, color = Tert_combine)) +
  geom_point() +
  stat_ellipse() + 
  theme_classic(base_size = 18) +
  labs(color = "Categorization of Combined Dietary Antioxidant Intake") +
   scale_color_manual(
    values = c("Combine Low" = "goldenrod2", "Combine Medium" = "steelblue", "Combine High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  )
p_combine

# PERMANOVA test
# Single variable
set.seed(421)
stats_univar_combine = adonis2(ps_unweighted_unifrac ~ Tert_combine, data = parkinsons_metadata)

# Factor in confounding variables
set.seed(421)
stats_multivar_combine = adonis2(ps_unweighted_unifrac ~ Tert_combine + Age + Sex + entacapone, data = parkinsons_metadata, by = "margin")

# Combine into a table
stats_combine = bind_rows("Univariate" = stats_univar_combine %>% as.data.frame() %>% 
                            rownames_to_column("Variable"),
                          "Multivariate" = stats_multivar_combine %>% as.data.frame() %>%
                            rownames_to_column("Variable"),
                          .id = "Model") # first column is Model, either Uni or Multi

stats_combine = stats_combine %>% rename(Pval = `Pr(>F)`) %>% 
  filter(!is.na(Pval)) # remove irrelevant lines
```

#### "Combine Low" vs. "Combine High"

```{r}
# List samples that belong to the categories of interest (low and high)
to_compare_combine_LH = c("Combine Low", "Combine High")

# List samples that belong to these categories of interest 
samples_to_keep_combine_LH = parkinsons_metadata %>% filter(Tert_combine %in% to_compare_combine_LH) %>%
  rownames()

# Subset the distance matrix to only include those two categories of interest
ps_unweighted_unifrac_sub_combine_LH = as.matrix(ps_unweighted_unifrac)[samples_to_keep_combine_LH, samples_to_keep_combine_LH] %>% as.dist()

# Run a PERMANOVA test again and account for the real confounding variables
set.seed(421)
stats_unweighted_multivar_combine_LH = adonis2(ps_unweighted_unifrac_sub_combine_LH ~ Tert_combine + Age + entacapone + Sex,
                                               data = parkinsons_metadata %>% filter(Tert_combine %in% to_compare_combine_LH)) # p-value is 0.077
```
