---
title: "Termina Code Record"
output: html_document
date: "2026-03-13"
---

This R markdown is created to record all the codes that were used to run analysis in QIIME2 and PICRUSt2.

## QIIME2

-   Log in to the container for our group project

    ssh [root\@10.34.36.92](mailto:root@10.34.36.92){.email}

    Password: Biome2196

-   Import and demultiplex the dataset in the main directory and move the demultiplexed dataset to /work/group_project directory

    qiime tools import\
    --type "SampleData[SequencesWithQuality]"\
    --input-format SingleEndFastqManifestPhred33V2\
    --input-path datasets/project_2/parkinsons/parkinsons_manifest.tsv\
    --output-path work/group_project/demux_seqs.qza

-   Working in /work/group_project directory

    qiime demux summarize\
    --i-data demux_seqs.qza\
    --o-visualization demux_seqs.qzv

-   Determine ASVs with DADA2

    qiime dada2 denoise-single\
    --i-demultiplexed-seqs demux_seqs.qza\
    --p-trim-left 0\
    --p-trunc-len 251\
    --o-representative-sequences rep-seqs.qza\
    --o-table table.qza\
    --o-denoising-stats stats.qza

-   Visualize DADA2 stats

    qiime metadata tabulate\
    --m-input-file stats.qza\
    --o-visualization stats.qzv

-   Visualize ASVs stats

    qiime feature-table summarize\
    --i-table table.qza\
    --o-visualization table.qzv\
    --m-sample-metadata-file /datasets/project_2/parkinsons/parkinsons_metadata.txt

    qiime feature-table tabulate-seqs\
    --i-data rep-seqs.qza\
    --o-visualization rep-seqs.qzv

-   Each of us can run this on our own laptops

    scp [root\@10.34.36.92](mailto:root@10.34.36.92){.email}:/work/group_project/rep-seqs.qzv .

    scp [root\@10.34.36.92](mailto:root@10.34.36.92){.email}:/work/group_project/table.qzv .

    scp [root\@10.34.36.92](mailto:root@10.34.36.92){.email}:/work/group_project/stats.qzv .

-   silva-138-99-seqs.qza: reference file of all known 16S sequence

    qiime feature-classifier extract-reads\
    --i-sequences /datasets/silva_ref_files/silva-138-99-seqs.qza\
    --p-f-primer GTGCCAGCMGCCGCGGTAA\
    --p-r-primer GGACTACHVHHHTWTCTAAT\
    --p-trunc-len 251\
    --o-reads ref-seqs-trimmed.qza

-   Annotate taxonomy with our new trimmed classifier (ref-seqs-trimmed.qza)

    qiime feature-classifier fit-classifier-naive-bayes\
    --i-reference-reads ref-seqs-trimmed.qza\
    --i-reference-taxonomy /datasets/silva_ref_files/silva-138-99-tax.qza\
    --o-classifier classifier.qza

-   Apply to our dataset by using the trained classifier to assign taxonomy to our reads (rep-seqs.qza)

    qiime feature-classifier classify-sklearn\
    --i-classifier classifier.qza\
    --i-reads rep-seqs.qza\
    --o-classification taxonomy.qza

-   Remove mitochondria and chloroplast sequences

    qiime taxa filter-table\
    --i-table table.qza\
    --i-taxonomy taxonomy.qza\
    --p-exclude mitochondria,chloroplast\
    --o-filtered-table table-no-mitochondria-no-chloroplast.qza

-   Remove under-annotated ASVs (reads that are only annotated to bacteria or are annotated as unassigned)

    qiime taxa filter-table\
    --i-table table-no-mitochondria-no-chloroplast.qza\
    --i-taxonomy taxonomy.qza\
    --p-include p\_\_\
    --o-filtered-table table_with_at_least_phylum_info.qza

-   Sample-based filtering to remove “failed” samples

    qiime feature-table filter-samples\
    --i-table table_with_at_least_phylum_info.qza\
    --p-min-frequency 55\
    --o-filtered-table sample-frequency-filtered-table.qza

-   Metadata-based filtering: since we will focus on only the PD cohort in our downstream analyses, we will filter out the control individuals

    qiime feature-table filter-samples\
    --i-table sample-frequency-filtered-table.qza\
    --m-metadata-file /datasets/project_2/parkinsons/parkinsons_metadata.txt\
    --p-where "[Disease] = 'PD'"\
    --o-filtered-table PD-filtered-table.qza

    qiime feature-table summarize\
    --i-table PD-filtered-table.qza\
    --o-visualization PD-filtered-table.qzv\
    --m-sample-metadata-file /datasets/project_2/parkinsons/parkinsons_metadata.txt

-   Transfer the PD-filtered-table.qzv to our local computers

    scp [root\@10.34.36.92](mailto:root@10.34.36.92){.email}:/work/group_project/PD-filtered-table.qzv .

-   Visualize PD-filtered-table.qzv using the QIIME2 View. Based on the “frequency per sample”, which shows the number of reads per sample, the 3rd quartile is 14,230 (75% of the samples have reads that are less than 14,230), and the maximum number of reads is 24,026. Therefore, a sampling depth of 24,000 will be utilized.

-   Generate a tree for phylogenetic diversity analyses

    qiime phylogeny align-to-tree-mafft-fasttree\
    --i-sequences rep-seqs.qza\
    --o-alignment aligned-rep-seqs.qza\
    --o-masked-alignment masked-aligned-rep-seqs.qza\
    --o-tree unrooted-tree.qza\
    --o-rooted-tree rooted-tree.qza

-   Generate the alpha-rarefaction curve

    qiime diversity alpha-rarefaction\
    --i-table table.qza\
    --i-phylogeny rooted-tree.qza\
    --p-max-depth 24000\
    --m-metadata-file /datasets/project_2/parkinsons/parkinsons_metadata.txt\
    --o-visualization alpha_rarefaction_PD_filtered.qzv

-   Transfer the alpha_rarefaction_PD_filtered.qzv to our local computers and open it using QIIME2 View

    scp [root\@10.34.36.92](mailto:root@10.34.36.92){.email}:/work/group_project/alpha_rarefaction_PD_filtered.qzv .

-   Filter the PD-filtered-table.qza to remove all the features with 5 or lower counts. This will make the PICRUSt2 analysis much faster

    qiime feature-table filter-features\
    --i-table PD-filtered-table.qza\
    --p-min-frequency 5\
    --o-filtered-table feature-frequency-PD-filtered-table.qza

-   Create a new directory called “picrust” and store the “feature-frequency-PD-filtered-table.qza” file and “rep-seqs.qza” file in the picrust folder

    mkdir picrust_PD_filtered qiime tools export\
    --input-path feature-frequency-PD-filtered-table.qza\
    --output-path picrust_PD_filtered

    qiime tools export\
    --input-path rep-seqs.qza\
    --output-path picrust_PD_filtered

## PICRUSt2

-   Switch to PICRUSt2 environment

    conda deactivate conda activate picrust2

-   Run PICRUSt2

    picrust2_pipeline.py\
    -s picrust_PD_filtered/dna-sequences.fasta\
    -i picrust_PD_filtered/feature-table.biom\
    -o picrust_out_PD_filtered

## Export files that are needed for downstream R analyses (convert .qza files to human readable files and export them)

```         
qiime tools export \
--input-path PD-filtered-table.qza \
--output-path .

qiime tools export \
--input-path taxonomy.qza \
--output-path export_PD_filtered

qiime tools export \
--input-path rooted-tree.qza \
--output-path export_PD_filtered

biom convert \
-i feature-table.biom \
--to-tsv \
-o exports/feature-table.txt

gunzip picrust_out_PD_filtered/combined_EC_predicted.tsv.gz

gunzip picrust_out_PD_filtered/combined_KO_predicted.tsv.gz

gunzip picrust_out_PD_filtered/pathways_out/path_abun_unstrat.tsv

mv picrust_out_PD_filtered/*.tsv export_PD_filtered/

mv picrust_out_PD_filtered/pathways_out/path_abun_unstrat.tsv export_PD_filtered/
```

-   To export the file to our local computers

    scp -r [root\@10.34.36.92](mailto:root@10.34.36.92){.email}:/work/group_project/export_PD_filtered .
