---
title: "Alpha Diversity Analysis"
author: Yanting Xiong
output: html_document
---
## Library loading

```{r libraries, include = FALSE}
library(tidyverse)
library(phyloseq)
library(ggplot2)
library(dplyr)
library(vegan)
library(broom)
```

## Load the data

```{r load_data}
# Load in the filtered and wrangled Parkinson's metadata
parkinsons_metadata_filt_cat = read.csv('../../../Datasets/Metadata/parkinsons_metadata_filt_cat.csv', row.names = 1)

# Because we will be controlling for entacapone in downstream analyses and it contains NA values, they need to be removed from the filtered metadata
parkinsons_metadata_filt_cat_entacapone_NA_removed = parkinsons_metadata_filt_cat %>% filter(!is.na(entacapone))
# 10 PD individuals are removed after this filtering step because they do not have entacapone intakes recorded

# Load in feature table exported from QIIME2
counts = read.delim('../../../QIIME2_outputs/feature-table.txt', skip = 1, row.names = 1)

# Load in taxonomy table exported from QIIME2
taxonomy = read.delim('../../../QIIME2_outputs/taxonomy.tsv', row.names = 1)
```

## Make a Phyloseq object

```{r Create a Phyloseq object}
taxonomy_formatted = taxonomy %>% 
  separate(col = Taxon,
           into = c("Domain", "Phylum", "Class", "Order", "Family",
                    "Genus", "Species"),
           sep = ";", fill = "right") %>% 
  select(-Confidence) %>% 
  as.matrix()

counts_formatted = counts %>% as.matrix()

ps = phyloseq(sample_data(parkinsons_metadata_filt_cat_entacapone_NA_removed),
              otu_table(counts_formatted, taxa_are_rows = T),
              tax_table(taxonomy_formatted))
```

## Alpha rarefaction curve

```{r alpha_rarefaction}
# Alpha rarefaction curve
rarecurve(t(data.frame(ps@otu_table)),
          step = 1000)

# Based on the alpha rarefaction curve and the PD-filtered-table.qzv results, a sampling depth of 6515 will be chosen because at this sampling depth, only 14 samples are excluded from the analysis and we have retained 1,192,428 (50.04%) features in 183 (92.89%) samples at this specified sampling depth.

# Rarefy the data based on the rarefaction depth chosen
set.seed(421)
psrare = ps %>% rarefy_even_depth(sample.size = 6515, rngseed = 421)
```

## Alpha Diversity Analysis

### Beta carotene

```{r alpha_diversity_analysis_for_beta_carotene}
set.seed(421)

p_BC = plot_richness(psrare, x = "Tert_BC",
                     measures = c("Observed", "Shannon", "Chao1", "Simpson"),
                     color = "Tert_BC")
p_BC

# Modify the graph
# Pull the data from the plot:
pdata_BC = p_BC$data

pdata_BC$Tert_BC = fct_relevel(
  pdata_BC$Tert_BC,
  "BC Low",
  "BC Medium",
  "BC High"
)

str(pdata_BC) # variable denotes metric, value denotes value

# Graph the plot again
p_BC_formatted = pdata_BC %>% ggplot(aes(Tert_BC, 
                                         value, 
                                         fill = Tert_BC)) +
  geom_boxplot(outlier.shape = NA) + # Don't plot outlier points 
  geom_jitter(height = 0, width = 0.2, size = 0.03) + # Space the points out sideways, reducing overlap
  # Add some formatting
  theme_classic(base_size = 16) +
  facet_wrap(~ variable, ncol = 2, scales = "free_y") +
  ylab("Alpha Diversity Metrics") + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(fill = "Beta Carotene Intake Categorization") +
  scale_fill_manual(
    values = c("BC Low" = "goldenrod2", "BC Medium" = "steelblue", "BC High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  ) +
  scale_x_discrete(
    labels = c("BC Low" = "Low intake",
               "BC Medium" = "Medium intake",
               "BC High" = "High intake"))
p_BC_formatted

# Export the boxplots
ggsave("../../../Results/Figures/Aim_1/Alpha_diversity/Alpha diversity analysis of beta-carotene.png", plot = p_BC_formatted, width = 9, height = 10, dpi = 300)

comparisons_BC = list(c("BC High", "BC Low"),
                      c("BC High", "BC Medium"),
                      c("BC Low", "BC Medium"))

stats_BC = pdata_BC %>% group_by(variable) %>% # running each metric concurrently
  group_modify(~ {
    # now we'll run our single test for each of the above comparisons
    
    temp_stats = data.frame() # where we'll put our stats
    
    for (i in comparisons_BC) {
      temp = .x %>% filter(Tert_BC %in% i) 
      
      linear_regression = lm(formula = value ~ Tert_BC + Age + Sex + entacapone,
                             data = temp) %>% 
        broom::tidy(conf.int = TRUE) %>% 
        mutate(group1 = i[1], group2 = i[2],
            .before = "estimate")
      
      # add to temp_stats
      temp_stats = bind_rows(temp_stats, linear_regression) 
    }
    
    # add adjusted p-values
    temp_stats = temp_stats %>% 
      mutate(padj = p.adjust(p.value, method = "BH"), .after = "p.value")
    
    return(temp_stats)
  }
 ) %>% 
  ungroup()

View(stats_BC)

# Observed:
# BC low vs. BC high: p-value = 7.023892e-01; padj = 8.104491e-01
# BC medium vs. BC high: p-value = 6.866476e-01; padj = 8.104491e-01
# BC low vs. BC medium: p-value = 2.365073e-01; padj = 4.434512e-01

# Chao1:
# BC low vs. BC high: p-value = 5.667898e-01; padj = 7.728951e-01
# BC medium vs. BC high: p-value = 7.959221e-01; padj = 9.096956e-01
# BC low vs. BC medium: p-value = 2.215394e-01; padj = 4.153864e-01

# Shannon:
# BC low vs. BC high: p-value = 2.017657e-01; padj = 3.783107e-01
# BC medium vs. BC high: p-value = 8.973770e-02; padj = 1.922951e-01
# BC low vs. BC medium: p-value = 4.825191e-01; padj = 5.615900e-01

# Simpson:
# BC low vs. BC high: p-value = 1.570182e-01; padj = 3.364676e-01
# BC medium vs. BC high: p-value = 4.099289e-02; padj = 1.537233e-01
# BC low vs. BC medium: p-value = 5.254706e-01; padj = 6.786011e-01

```

### Alpha carotene

```{r alpha_diversity_analysis_for_alpha_carotene}
set.seed(421)
p_AC = plot_richness(psrare, x = "Tert_AC",
                     measures = c("Observed", "Shannon", "Chao1", "Simpson"),
                     color = "Tert_AC")
p_AC

# Modify the graph
# Pull the data from the plot:
pdata_AC = p_AC$data

pdata_AC$Tert_AC = fct_relevel(
  pdata_AC$Tert_AC,
  "AC Low",
  "AC Medium",
  "AC High"
)

str(pdata_AC) # variable denotes metric, value denotes value

# Graph the plot again
p_AC_formatted = pdata_AC %>% ggplot(aes(Tert_AC, 
                                         value, 
                                         fill = Tert_AC)) +
  geom_boxplot(outlier.shape = NA) + # Don't plot outlier points 
  geom_jitter(height = 0, width = 0.2, size = 0.03) + # Space the points out sideways, reducing overlap
  # Add some formatting
  theme_classic(base_size = 16) +
  facet_wrap(~ variable, ncol = 2, scales = "free_y") +
  ylab("Alpha Diversity Metrics") + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(fill = "Alpha Carotene Intake Categorization") +
  scale_fill_manual(
    values = c("AC Low" = "goldenrod2", "AC Medium" = "steelblue", "AC High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  ) +
  scale_x_discrete(
    labels = c("AC Low" = "Low intake",
               "AC Medium" = "Medium intake",
               "AC High" = "High intake"))
p_AC_formatted

# Export the boxplots
ggsave("../../../Results/Figures/Aim_1/Alpha_diversity/Alpha diversity analysis of alpha-carotene.png", plot = p_AC_formatted, width = 9, height = 10, dpi = 300)


comparisons_AC = list(c("AC High", "AC Low"),
                      c("AC High", "AC Medium"),
                      c("AC Low", "AC Medium"))

stats_AC = pdata_AC %>% group_by(variable) %>% # running each metric concurrently
  group_modify(~ {
    # now we'll run our single test for each of the above comparisons
    
    temp_stats = data.frame() # where we'll put our stats
    
    for (i in comparisons_AC) {
      temp = .x %>% filter(Tert_AC %in% i) 
      
      linear_regression = lm(formula = value ~ Tert_AC + Age + Sex + entacapone,
                             data = temp) %>% 
        broom::tidy(conf.int = T) %>% 
        mutate(group1 = i[1], group2 = i[2],
            .before = "estimate")
      
      # add to temp_stats
      temp_stats = bind_rows(temp_stats, linear_regression) 
    }
    
    # add adjusted p-values
    temp_stats = temp_stats %>% 
      mutate(padj = p.adjust(p.value, method = "BH"), .after = "p.value")
    
    return(temp_stats)
  }
 ) %>% 
  ungroup()

View(stats_AC)

# Observed:
# AC low vs. AC high: p-value = 7.749841e-01; padj = 9.577047e-01
# AC medium vs. AC high: p-value = 9.997709e-01; padj = 9.997709e-01
# AC low vs. AC medium: p-value = 7.739977e-01; padj = 9.577047e-01

# Chao1:
# AC low vs. AC high: p-value = 9.320260e-01; padj = 9.320260e-01
# AC medium vs. AC high: p-value = 7.959221e-01; padj = 9.096956e-01
# AC low vs. AC medium: p-value = 8.417970e-01; padj = 9.320260e-01

# Shannon:
# AC low vs. AC high: p-value = 3.623684e-01; padj = 5.621332e-01
# AC medium vs. AC high: p-value = 8.061908e-01; padj = 8.988026e-01
# AC low vs. AC medium: p-value = 4.952529e-01; padj = 6.190661e-01

# Simpson:
# AC low vs. AC high: p-value = 5.396503e-01; padj = 7.342411e-01
# AC medium vs. AC high: p-value = 8.953567e-01; padj = 9.319864e-01
# AC low vs. AC medium: p-value = 5.873929e-01; padj = 7.342411e-01

```

### Vitamin C

```{r alpha_diversity_analysis_for_vitamin_c}
set.seed(421)
p_VC = plot_richness(psrare, x = "Tert_VC",
                     measures = c("Observed", "Shannon", "Chao1", "Simpson"),
                     color = "Tert_VC")
p_VC

# Modify the graph
# Pull the data from the plot:
pdata_VC = p_VC$data

pdata_VC$Tert_VC = fct_relevel(
  pdata_VC$Tert_VC,
  "VC Low",
  "VC Medium",
  "VC High"
)

str(pdata_VC) # variable denotes metric, value denotes value

# Graph the plot again
p_VC_formatted = pdata_VC %>% ggplot(aes(Tert_VC, 
                                         value, 
                                         fill = Tert_VC)) +
  geom_boxplot(outlier.shape = NA) + # Don't plot outlier points 
  geom_jitter(height = 0, width = 0.2, size = 0.03) + # Space the points out sideways, reducing overlap
  # Add some formatting
  theme_classic(base_size = 16) +
  facet_wrap(~ variable, ncol = 2, scales = "free_y") +
  ylab("Alpha Diversity Metrics") + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(fill = "Vitamin C Intake Categorization") +
  scale_fill_manual(
    values = c("VC Low" = "goldenrod2", "VC Medium" = "steelblue", "VC High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  ) +
  scale_x_discrete(
    labels = c("VC Low" = "Low intake",
               "VC Medium" = "Medium intake",
               "VC High" = "High intake"))
p_VC_formatted

# Export the boxplots
ggsave("../../../Results/Figures/Aim_1/Alpha_diversity/Alpha diversity analysis of vitamin C.png", plot = p_VC_formatted, width = 9, height = 10, dpi = 300)


comparisons_VC = list(c("VC High", "VC Low"),
                      c("VC High", "VC Medium"),
                      c("VC Low", "VC Medium"))

stats_VC = pdata_VC %>% group_by(variable) %>% # running each metric concurrently
  group_modify(~ {
    # now we'll run our single test for each of the above comparisons
    
    temp_stats = data.frame() # where we'll put our stats
    
    for (i in comparisons_VC) {
      temp = .x %>% filter(Tert_VC %in% i) 
      
      linear_regression = lm(formula = value ~ Tert_VC + Age + Sex + entacapone,
                             data = temp) %>% 
        broom::tidy(conf.int = T) %>% 
        mutate(group1 = i[1], group2 = i[2],
            .before = "estimate")
      
      # add to temp_stats
      temp_stats = bind_rows(temp_stats, linear_regression) 
    }
    
    # add adjusted p-values
    temp_stats = temp_stats %>% 
      mutate(padj = p.adjust(p.value, method = "BH"), .after = "p.value")
    
    return(temp_stats)
  }
 ) %>% 
  ungroup()

View(stats_VC)

# Observed:
# VC low vs. VC high: p-value = 1.464693e-01; padj = 2.827983e-01
# VC medium vs. VC high: p-value = 8.000836e-02; padj = 2.000209e-01
# VC low vs. VC medium: p-value = 7.413906e-01; padj = 7.943471e-01

# Chao1:
# VC low vs. VC high: p-value = 1.115062e-01; padj = 2.389419e-01
# VC medium vs. VC high: p-value = 7.950082e-02; padj = 1.987521e-01
# VC low vs. VC medium: p-value = 8.455806e-01; padj = 8.479645e-01

# Shannon:
# VC low vs. VC high: p-value = 8.878042e-01; padj = 9.512188e-01
# VC medium vs. VC high: p-value = 1.169308e-01; padj = 2.505660e-01
# VC low vs. VC medium: p-value = 2.175952e-01; padj = 4.079910e-01

# Simpson:
# VC low vs. VC high: p-value = 9.341548e-01; padj = 9.341548e-01
# VC medium vs. VC high: p-value = 7.400270e-02; padj = 2.220081e-01
# VC low vs. VC medium: p-value = 1.776940e-01; padj = 4.442350e-01

```

### Vitamin A

```{r alpha_diversity_analysis_for_vitamin_a}
set.seed(421)
p_VA = plot_richness(psrare, x = "Tert_VA",
                     measures = c("Observed", "Shannon", "Chao1", "Simpson"),
                     color = "Tert_VA")
p_VA

# Modify the graph
# Pull the data from the plot:
pdata_VA = p_VA$data

pdata_VA$Tert_VA = fct_relevel(
  pdata_VA$Tert_VA,
  "VA Low",
  "VA Medium",
  "VA High"
)

str(pdata_VA) # variable denotes metric, value denotes value

# Graph the plot again
p_VA_formatted = pdata_VA %>% ggplot(aes(Tert_VA, 
                                         value, 
                                         fill = Tert_VA)) +
  geom_boxplot(outlier.shape = NA) + # Don't plot outlier points 
  geom_jitter(height = 0, width = 0.2, size = 0.03) + # Space the points out sideways, reducing overlap
  # Add some formatting
  theme_classic(base_size = 16) +
  facet_wrap(~ variable, ncol = 2, scales = "free_y") +
  ylab("Alpha Diversity Metrics") + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(fill = "Vitamin A Intake Categorization") +
  scale_fill_manual(
    values = c("VA Low" = "goldenrod2", "VA Medium" = "steelblue", "VA High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  ) +
  scale_x_discrete(
    labels = c("VA Low" = "Low intake",
               "VA Medium" = "Medium intake",
               "VA High" = "High intake"))
p_VA_formatted

# Export the boxplots
ggsave("../../../Results/Figures/Aim_1/Alpha_diversity/Alpha diversity analysis of vitamin A.png", plot = p_VA_formatted, width = 9, height = 10, dpi = 300)


comparisons_VA = list(c("VA High", "VA Low"),
                      c("VA High", "VA Medium"),
                      c("VA Low", "VA Medium"))

stats_VA = pdata_VA %>% group_by(variable) %>% # running each metric concurrently
  group_modify(~ {
    # now we'll run our single test for each of the above comparisons
    
    temp_stats = data.frame() # where we'll put our stats
    
    for (i in comparisons_VA) {
      temp = .x %>% filter(Tert_VA %in% i) 
      
      linear_regression = lm(formula = value ~ Tert_VA + Age + Sex + entacapone,
                             data = temp) %>% 
        broom::tidy(conf.int = T) %>% 
        mutate(group1 = i[1], group2 = i[2],
            .before = "estimate")
      
      # add to temp_stats
      temp_stats = bind_rows(temp_stats, linear_regression) 
    }
    
    # add adjusted p-values
    temp_stats = temp_stats %>% 
      mutate(padj = p.adjust(p.value, method = "BH"), .after = "p.value")
    
    return(temp_stats)
  }
 ) %>% 
  ungroup()

View(stats_VA)

# Observed:
# VA low vs. VA high: p-value = 4.180527e-01; padj = 6.270790e-01
# VA medium vs. VA high: p-value = 6.155514e-01; padj = 6.595194e-01
# VA low vs. VA medium: p-value = 2.587613e-01; padj = 4.851775e-01

# Chao1:
# VA low vs. VA high: p-value = 3.623659e-01; padj = 5.707566e-01
# VA medium vs. VA high: p-value = 7.176124e-01; padj = 7.688704e-01
# VA low vs. VA medium: p-value = 2.574575e-01; padj = 4.827328e-01

# Shannon:
# VA low vs. VA high: p-value = 9.869282e-01; padj = 9.869282e-01
# VA medium vs. VA high: p-value = 8.446451e-01; padj = 9.869282e-01
# VA low vs. VA medium: p-value = 8.993830e-01; padj = 9.869282e-01

# Simpson:
# VA low vs. VA high: p-value = 5.088437e-01; padj = 6.938778e-01
# VA medium vs. VA high: p-value = 9.916369e-01; padj = 9.916369e-01
# VA low vs. VA medium: p-value = 3.221053e-01; padj = 5.461453e-01

```

### Vitamin E

```{r alpha_diversity_analysis_for_vitamin_e}
set.seed(421)
p_VE = plot_richness(psrare, x = "Tert_VE",
                     measures = c("Observed", "Shannon", "Chao1", "Simpson"),
                     color = "Tert_VE")
p_VE

# Modify the graph
# Pull the data from the plot:
pdata_VE = p_VE$data

pdata_VE$Tert_VE = fct_relevel(
  pdata_VE$Tert_VE,
  "VE Low",
  "VE Medium",
  "VE High"
)

str(pdata_VE) # variable denotes metric, value denotes value

# Graph the plot again
p_VE_formatted = pdata_VE %>% ggplot(aes(Tert_VE, 
                                         value, 
                                         fill = Tert_VE)) +
  geom_boxplot(outlier.shape = NA) + # Don't plot outlier points 
  geom_jitter(height = 0, width = 0.2, size = 0.03) + # Space the points out sideways, reducing overlap
  # Add some formatting
  theme_classic(base_size = 16) +
  facet_wrap(~ variable, ncol = 2, scales = "free_y") +
  ylab("Alpha Diversity Metrics") + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(fill = "Vitamin E Intake Categorization") +
  scale_fill_manual(
    values = c("VE Low" = "goldenrod2", "VE Medium" = "steelblue", "VE High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  ) +
  scale_x_discrete(
    labels = c("VE Low" = "Low intake",
               "VE Medium" = "Medium intake",
               "VE High" = "High intake"))
p_VE_formatted

# Export the boxplots
ggsave("../../../Results/Figures/Aim_1/Alpha_diversity/Alpha diversity analysis of vitamin E.png", plot = p_VE_formatted, width = 9, height = 10, dpi = 300)


comparisons_VE = list(c("VE High", "VE Low"),
                      c("VE High", "VE Medium"),
                      c("VE Low", "VE Medium"))

stats_VE = pdata_VE %>% group_by(variable) %>% # running each metric concurrently
  group_modify(~ {
    # now we'll run our single test for each of the above comparisons
    
    temp_stats = data.frame() # where we'll put our stats
    
    for (i in comparisons_VE) {
      temp = .x %>% filter(Tert_VE %in% i) 
      
      linear_regression = lm(formula = value ~ Tert_VE + Age + Sex + entacapone,
                             data = temp) %>% 
        broom::tidy(conf.int = T) %>% 
        mutate(group1 = i[1], group2 = i[2],
            .before = "estimate")
      
      # add to temp_stats
      temp_stats = bind_rows(temp_stats, linear_regression) 
    }
    
    # add adjusted p-values
    temp_stats = temp_stats %>% 
      mutate(padj = p.adjust(p.value, method = "BH"), .after = "p.value")
    
    return(temp_stats)
  }
 ) %>% 
  ungroup()

View(stats_VE)

# Observed:
# VE low vs. VE high: p-value = 4.004398e-01; padj = 5.606224e-01
# VE medium vs. VE high: p-value = 3.774140e-01; padj = 5.606224e-01
# VE low vs. VE medium: p-value = 1.777419e-01; padj = 3.332660e-01

# Chao1:
# VE low vs. VE high: p-value = 3.657044e-01; padj = 5.884821e-01
# VE medium vs. VE high: p-value = 4.547703e-01; padj = 5.884821e-01
# VE low vs. VE medium: p-value = 1.878331e-01; padj = 3.521870e-01

# Shannon:
# VE low vs. VE high: p-value = 4.257780e-01; padj = 6.063406e-01
# VE medium vs. VE high: p-value = 8.282633e-02; padj = 1.774850e-01
# VE low vs. VE medium: p-value = 5.231307e-01; padj = 6.063406e-01

# Simpson:
# VE low vs. VE high: p-value = 2.706757e-01; padj = 4.384506e-01
# VE medium vs. VE high: p-value = 9.242231e-02; padj = 2.310558e-01
# VE low vs. VE medium: p-value = 7.952424e-01; padj = 8.520454e-01

```

### Combine all five dietary antioxidants together

```{r alpha_diversity_analysis_for_all_dietary_antioxidants}
set.seed(421)
p_combine = plot_richness(psrare, x = "Tert_combine",
                          measures = c("Observed", "Shannon", "Chao1", "Simpson"),
                          color = "Tert_combine")
p_combine

# Modify the graph
# Pull the data from the plot:
pdata_combine = p_combine$data

pdata_combine$Tert_combine = fct_relevel(
  pdata_combine$Tert_combine,
  "Combine Low",
  "Combine Medium",
  "Combine High"
)

str(pdata_combine) # variable denotes metric, value denotes value

# Graph the plot again
p_combine_formatted = pdata_combine %>% ggplot(aes(Tert_combine, 
                                                   value, 
                                                   fill = Tert_combine)) +
  geom_boxplot(outlier.shape = NA) + # Don't plot outlier points 
  geom_jitter(height = 0, width = 0.2, size = 0.03) + # Space the points out sideways, reducing overlap
  # Add some formatting
  theme_classic(base_size = 16) +
  facet_wrap(~ variable, ncol = 2, scales = "free_y") +
  ylab("Alpha Diversity Metrics") + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(fill = "Combine Dietary Antioxidant Intake Categorization") +
  scale_fill_manual(
    values = c("Combine Low" = "goldenrod2", "Combine Medium" = "steelblue", "Combine High" = "indianred3"),
    labels = c("Low intake", "Medium intake", "High intake")
  ) +
  scale_x_discrete(
    labels = c("Combine Low" = "Low intake",
               "Combine Medium" = "Medium intake",
               "Combine High" = "High intake"))
p_combine_formatted

# Export the boxplots
ggsave("../../../Results/Figures/Aim_1/Alpha_diversity/Alpha diversity analysis of combined.png", plot = p_combine_formatted, width = 9, height = 10, dpi = 300)


comparisons_combine = list(c("Combine High", "Combine Low"),
                           c("Combine High", "Combine Medium"),
                           c("Combine Low", "Combine Medium"))

stats_combine = pdata_combine %>% group_by(variable) %>% # running each metric concurrently
  group_modify(~ {
    # now we'll run our single test for each of the above comparisons
    
    temp_stats = data.frame() # where we'll put our stats
    
    for (i in comparisons_combine) {
      temp = .x %>% filter(Tert_combine %in% i) 
      
      linear_regression = lm(formula = value ~ Tert_combine + Age + Sex + entacapone,
                             data = temp) %>% 
        broom::tidy(conf.int = T) %>% 
        mutate(group1 = i[1], group2 = i[2],
            .before = "estimate")
      
      # add to temp_stats
      temp_stats = bind_rows(temp_stats, linear_regression) 
    }
    
    # add adjusted p-values
    temp_stats = temp_stats %>% 
      mutate(padj = p.adjust(p.value, method = "BH"), .after = "p.value")
    
    return(temp_stats)
  }
 ) %>% 
  ungroup()

View(stats_combine)

# Observed:
# Combine low vs. Combine high: p-value = 3.236432e-01; padj = 4.597522e-01
# Combine medium vs. Combine high: p-value = 8.950680e-01; padj = 8.950680e-01
# Combine low vs. Combine medium: p-value = 1.491989e-01; padj = 3.197118e-01

# Chao1:
# Combine low vs. Combine high: p-value = 2.638400e-01; padj = 3.957600e-01
# Combine medium vs. Combine high: p-value = 9.180755e-01; padj = 9.180755e-01
# Combine low vs. Combine medium: p-value = 1.202339e-01; padj = 2.576441e-01

# Shannon:
# Combine low vs. Combine high: p-value = 4.210305e-01; padj = 7.017175e-01
# Combine medium vs. Combine high: p-value = 5.596820e-01; padj = 7.256494e-01
# Combine low vs. Combine medium: p-value = 6.826679e-01; padj = 7.876937e-01

# Simpson:
# Combine low vs. Combine high: p-value = 1.718010e-01; padj = 4.295026e-01
# Combine medium vs. Combine high: p-value = 7.055524e-01; padj = 9.238496e-01
# Combine low vs. Combine medium: p-value = 8.316421e-01; padj = 9.238496e-01

```